- name: setup pkgs for all
  hosts: all
  pre_tasks:
  - name: install dependency packages
    apt:
      pkg:
        - iproute2 # dependency of wg-quick and some facts
      update_cache: yes
  tasks:
  - name: install packages
    apt:
      pkg:
        - iptables
        - wireguard
        - iputils-ping
        - dnsutils

- name: setup pkgs for CLIENTS
  hosts: all:!vpn-server
  vars:
    server_pubkey: Ig0GsW5wZw6MtmrxNtgvILiEWpzOkXOoMk1CW180klo=
  tasks:
  - name: generate private key
    shell:
      cmd: umask 077 && wg genkey | tee privatekey | wg pubkey > publickey
      chdir: /etc/wireguard
      creates: /etc/wireguard/publickey
  - name: get private key
    command: cat /etc/wireguard/privatekey
    register: privatekey_contents
    changed_when: False
  - name: set private key fact
    set_fact:
      privkey: "{{ privatekey_contents.stdout }}"
  - name: get public key
    command: cat /etc/wireguard/publickey
    register: publickey_contents
    changed_when: False
    tags: vpn-server-template
  - name: set public key fact
    set_fact:
      pubkey: "{{ publickey_contents.stdout }}"
    tags: vpn-server-template
  - name: create client wireguard config
    template:
      dest: /etc/wireguard/wg0.conf
      src: client_wg0.conf.j2
      owner: root
      group: root
      mode: '0600'
  - name: start wireguard
    shell: wg-quick down wg0; wg-quick up wg0

- name: setup vpn server
  hosts: vpn-server
  vars:
    server_privkey: cF/oyCQMnn3NBpHJkKZZRlwbmDLYZOvwmPnvfhF061k=
    server_pubkey: Ig0GsW5wZw6MtmrxNtgvILiEWpzOkXOoMk1CW180klo=
  tasks:
  - name: enable and persist ip forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      state: present
      sysctl_set: yes
      reload: yes
  - name: create server wireguard config
    template:
      dest: /etc/wireguard/wg0.conf
      src: server_wg0.conf.j2
      owner: root
      group: root
      mode: '0600'
    tags: vpn-server-template
  - name: start wireguard
    shell: wg-quick down wg0; wg-quick up wg0
